### ISSUE TITLE
Unexpected client behaviour Error Code: 268 while erasing

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#34]
On `v0.5.0` boards, erasing a small number of curves and straight lines on a persistent board on an iPad, was almost immediately disconnected with this error.

![IMG_1223190F73A0-1](https://user-images.githubusercontent.com/320329/148829885-f4a77b73-d024-4e9b-b874-b63cccba7507.jpeg)

**Comment by dmurfet** [comment]
This is reproducible, I have now done this twice (erase the 8-fold board, then get this error when I click on the white pen tool) and had the same error code from erasing the board and writing one sentence of text using the white pen tool.

The first two times I didn't have another player in the server, but the last time I see only `Players::onRemoteSysStats` in the server log.

**Comment by dmurfet** [comment]
Also reproduced it on my Macbook Pro. Write some text on the 8-fold board in TRS, erase it and then select the white pen tool, instant crash.

**Comment by dmurfet** [comment]
My feeling is that this is probably a symptom rather than a cause, since it looks like some script can't find the Player that crashed out, but it might be useful nonetheless (I saw this on the server log of a player still in the world after the other player crashed out with `268`.

<img width="750" alt="Screen Shot 2022-01-11 at 5 56 36 am" src="https://user-images.githubusercontent.com/320329/148831140-1e2b9cba-ecfb-424d-a6a9-258a5b8b14b1.png">

**Comment by billy-price** [comment]
This may or may not be related, but when I join TRS on the iPad, then join on my computer, my iPad sees only myself, not my computer player. My computer sees both players.
My iPad eventually sees the computer player after about a minute, which seems to be exactly when the persistent boards load.

When I say I can't see the computer player, I mean both that there character isn't there, and also the player doesn't appear in the player list at the top right.

**Comment by billy-price** [comment]
I've found a simpler way to get kicked. If you just draw a very long squiggly continuous curve like this you get kicked after about the second or third row.

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/31099215/148881374-7e5d4ac4-09c2-4438-83bd-7ef43b1aedcf.png">

If you do this same thing but drawing hundreds of smaller curves, you don't seem to get kicked. I think this is because theres' more time between strokes to catch up on the task, not sure though.

When I try and recreate the erasing kick behaviour, it doesn't seem to happen when I start from a fresh board. It tends to happen more when there's persistent lines already on the board, and may or may not require closing and reopening the board. I haven't been able to trigger the problem while erasing as consistently.

**Comment by billy-price** [comment]
I cannot recreate the kicking on other boards without the 8 subscribers.

**Comment by dmurfet** [comment]
I just noticed that Google analytics captured some useful logging messages

<img width="663" alt="Screen Shot 2022-01-11 at 3 49 54 pm" src="https://user-images.githubusercontent.com/320329/148888490-40add61b-5204-4c85-9645-59955f64d4aa.png">

**Comment by billy-price** [comment]
@EthanCurtiss identified that the use of `GetChildren` in the FreeHand drawing task update was occupying the server for too long, which it must trace back to the client that triggered the update remote event and kick them. This was a linear time operation in the number of lines, and has been fixed here 11f3be0.

This explains the kicking and ping spiking that occurs when drawing a very very long curve.

Erasing also does a lot of calls to `GetChildren`, both on the server and the client. Previously it was just the client that had to iterate over every curve, and it would tell the server which lines inside which curves to erase.  But this requires sending a lot of data to the server, instead of just the eraser positions and radius, and doesn't account for having multiple subscriber boards in different states.

It would be better if the server could perform the erasing less frequently than every frame, and group a bunch of eraser positions into one when iterating over all of the lines.

Another improvement would be to localise the erasing. Maintaining something like a quad-tree so that only the lines that a "near" the eraser get checked for intersection would be a massive improvement. But quad-trees are for organising points, not regions. I think a problem specific solution would be better.
