### ISSUE TITLE
Need clear board tool

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#8]
Until the eraser is much more performant than it is now, it is hostile to ask users to clear the board by erasing. Let's not sacrifice the user experience in the hope this magically improves.

**Comment by billy-price** [comment]
Fair, I'll put a clear board button (related issue, button crowding).
What's your assessment of the eraser performance? To me it's laggy but better than it was. I haven't experienced a genuine *stall*.

Should probably implement something like a quad-tree in future to *localise* the erasing.

**Comment by metauni** [comment]
The eraser performance has improved a lot in recent versions, but it's still not good enough to obviate a clear tool. Since clearing will always be faster, I think the eraser performance has to be *amazing* and buttery smooth before I'll switch to thinking the erasing ritual is worth the inconvenience.

**Comment by billy-price** [comment]
I wouldn't describe real-world erasing as "amazing and buttery smooth" lol.

I will begrudgingly re-add the clear board button, but I promise you that if you turned around while doing this, all eyes would be watching that squeegee go back-and-forth, back-and-forth... https://youtu.be/sQyDI76ppY4?t=1007

It's so sad to see all the lines just disappear in an instant!

**Comment by dmurfet** [comment]
Added in 12d5701ecb7be2aad61d86d856dffe78d6d2b359.
